version: "1"
services:
  app:
    build:
      context: .
    ports:
      - "5000"

  nginx:
    container_name: nginx_container
    image: nginx:1.25.3-alpine-slim
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app
    ports:
      - "80:80"
